steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/helloworldimage','.']
  env: 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  dir: 'examples/helloworld'
  timeout: 500s
logsBucket: 'gs://buck113'
images: ['gcr.io/$PROJECT_ID/helloworldimage']